import { useState } from "react";
import { LineChart, fmt, signed } from "./charts";
import { StrategyName } from "./strategy-name";
const elapsed=(s:number)=>s<60?`${Math.round(s)} s`:s<3600?`${Math.floor(s/60)} min`:`${Math.floor(s/3600)} h ${Math.floor(s%3600/60)} min`;
const stages:Record<string,string>={WAIT_FX:"Attente du change de référence",WAIT_FEED:"Attente de données exploitables",STALE_BOOK:"Carnet trop ancien",RISK_OFF:"Entrées bloquées par le garde global",STABILIZING:"Stabilisation des données et du signal",EVALUATING:"Évaluation des signaux",POSITIONS_OPEN:"Positions suivies",ENTRY_FILTERS:"Signal présent ; confirmation, spread, capacité ou cooldown requis",WAIT_SIGNAL:"Aucun nouveau signal au seuil requis"};
const causes:Record<string,string>={DIVERSITY_WARMUP:"Historique insuffisant pour mesurer la diversité",INSUFFICIENT_DIVERSITY:"Diversité effective des signaux inférieure à 1",RECOVERY_CONFIRMATION:"Reprise : trois observations consécutives du même état attendues",FEED_STALE:"Données trop anciennes",FEED_WAITING:"Flux en attente",FEED_RESYNC:"Carnet en resynchronisation"};
const exits:Record<string,string>={risk_off:"Garde global de risque",exposure_limit:"Limite d’exposition",strategy_retired:"Stratégie retirée",stop_loss:"Stop de protection",take_profit:"Objectif atteint",max_holding:"Durée maximale",signal_decay:"Signal affaibli ou inversé",pair_risk_or_funding_exit:"Risque ou funding de la couverture"};
const explanations:Record<string,string>={Momentum:"Suit le mouvement récent du prix.",Trend:"Suit la tendance avec un signal normalisé.","Mean reversion":"Teste un retour après un mouvement de prix.",Breakout:"Combine mouvement du prix et flux de transactions.","Order flow":"Suit le déséquilibre des transactions exécutées.",Microprice:"Exploite le prix pondéré du carnet et le spread.","Book pressure":"Exploite le déséquilibre pondéré du carnet.",Volatility:"Ajuste un signal de mouvement à la volatilité."};
export type SharedPortfolioState = {
 observed_at?:number;
 market_diagnostics?:Array<{symbol:string;stage:string;causes:string[];age_seconds:number;remaining_seconds?:number;eligible_signals:number}>;
 exit_summary?:{total:number;median_seconds:number|null;reasons:Record<string,number>};
 comparison?:{start_equity_eur:number;active_equity_eur:number;fixed_equity_eur:number;gain_since_start_eur:number;delta_vs_fixed_eur:number;closed_since_start:number;status:string;started_at:number}|null;
 allocation_feedback?:{enabled:boolean;groups:Array<{group:string;trades:number;net_eur:number;fees_eur:number;scale:number;status:string}>;decisions:Array<{ts:number;group:string;scale:number;net_eur:number;trades:number}>};
 initial_eur:number;equity_eur:number;pnl_eur:number;cash_eur:number;available_eur:number;margin_eur:number;gross_exposure_eur:number;net_exposure_eur:number;leverage:number;max_leverage:number;fees_eur:number;funding_eur:number;funding_unobserved_seconds:number;closed_count:number;status:string;error:string;pair_status:string;gamma_status:string;
 fx:{usd_per_eur:number;date:string}|null;
 positions:Array<{id:number;strategy_id:string;kind:string;opened_at:number;policy?:{family?:string;horizon?:number;max_holding_seconds?:number;stop_loss_bps?:number;take_profit_bps?:number};net_eur:number;fresh:boolean;delta_units:number|null;legs:Array<{instrument:string;kind:string;qty:number;entry:number;mark:number;marked_at:number}>}>;
 closed:Array<{id:number;strategy_id:string;kind:string;net_eur:number;fees_eur:number;opened_at?:number;closed_at:number;reason:string;exit_context?:{causes?:string[]}|null}>;
 history:Array<{ts:number;equity_eur:number}>;
};
export function SharedPortfolioPanel({p}:{p:SharedPortfolioState}) {
 const [showHistory,setShowHistory]=useState(true);
 return <section className="darwin-card shared-portfolio" aria-label="Portefeuille commun Darwin">
  <div className="darwin-card-head"><h3>Mon portefeuille Darwin</h3><span>Hyperliquid · PAPER · EUR</span></div>
  <p>Un seul capital partagé entre toutes les stratégies et tous les marchés. Conservé entre les cycles et les redémarrages.</p>
  {p.error&&<p role="alert">{p.error}</p>}
  <div className="darwin-kpis">
   <div><small>CAPITAL INITIAL</small><b>{fmt(p.initial_eur)} €</b><span>Démarrage de ce portefeuille</span></div>
   <div><small>VALEUR ACTUELLE</small><b>{fmt(p.equity_eur)} €</b><span className={p.pnl_eur>=0?"positive":"negative"}>{signed(p.pnl_eur)} € · {signed(p.pnl_eur/p.initial_eur*100)} %</span></div>
   <div><small>POSITIONS EN COURS</small><b>{p.positions.length}</b><span>{p.positions.reduce((n,x)=>n+x.legs.length,0)} jambes · {p.closed_count} positions clôturées</span></div>
   <div><small>LEVIER BRUT / LIMITE</small><b>{fmt(p.leverage)}× / 3×</b><span>{fmt(p.gross_exposure_eur)} € exposés · {fmt(Math.max(0,p.available_eur))} € disponibles</span></div>
  </div>
  <p className="panel-note">Frais déduits : {fmt(p.fees_eur)} € · funding estimé : {signed(p.funding_eur)} €. {p.positions.some(x=>!x.fresh)&&<strong>Valorisations périmées : attente des carnets ; aucune exécution sur ces données.</strong>}</p>
  <button className="toggle" onClick={()=>setShowHistory(!showHistory)}>{showHistory?"Masquer":"Voir"} l’évolution du capital</button>
  {showHistory&&<LineChart label="Capital commun · EUR" values={p.history.map(x=>x.equity_eur)} times={p.history.map(x=>x.ts)} color="#edb18b"/>}
  <section aria-label="Positions en cours" className="portfolio-live"><h4>Positions en cours · {p.positions.length}</h4>
   {!p.positions.length&&<div className="portfolio-empty"><b>Le portefeuille est actuellement sans position.</b><p>Les raisons observées par marché sont affichées ci-dessous.</p></div>}
   <div className="portfolio-position-grid">{p.positions.map(x=><article className="portfolio-position" key={x.id}>
    <header><b>{x.kind==="delta_neutral"?"Couverture HYPE":<StrategyName id={x.strategy_id}/>}</b><strong className={x.net_eur>=0?"positive":"negative"}>{signed(x.net_eur)} €</strong></header>
    <p>{x.kind==="delta_neutral"?"Spot acheté et perp vendu, même quantité de HYPE.":explanations[x.policy?.family??""]??"Allocation directionnelle du portefeuille."}</p>
    {x.legs.map(l=><div className="portfolio-leg" key={l.instrument}><b>{l.instrument.replace("perp:","Perp ").replace("spot:","Spot ")} · {l.qty>0?"LONG":"SHORT"}</b><span>{fmt(Math.abs(l.qty),6)} unités</span><span>Entrée {fmt(l.entry)} → prix actuel {fmt(l.mark)} USD</span></div>)}
    <p><b>Ouverte depuis {elapsed(Math.max(0,(p.observed_at??Date.now()/1000)-x.opened_at))}</b> · {new Date(x.opened_at*1000).toLocaleString()}</p>
    {x.kind==="directional"&&<><p>Signal : {elapsed(x.policy?.horizon??0)} · détention maximale : {elapsed(x.policy?.max_holding_seconds??0)}</p><p>Stop : {fmt((x.policy?.stop_loss_bps??0)/100)} % · objectif : {fmt((x.policy?.take_profit_bps??0)/100)} %</p></>}
    <small>{x.fresh?"Position encore ouverte à la dernière observation. Les gardes de risque et conditions de sortie restent prioritaires.":"Prix périmé : attente d’un carnet frais pour réévaluer et exécuter."} Résultat marqué après frais d’entrée et funding estimé ; frais de sortie non encore déduits.</small>
   </article>)}</div>
   <div className="portfolio-market-grid">{p.market_diagnostics?.map(d=><article key={d.symbol}><b>{d.symbol.replace("USDT","")}</b><p>{d.age_seconds>15?"Diagnostic ancien — attente d’une nouvelle observation":stages[d.stage]??d.stage}</p>{d.causes.map(c=><small key={c}>{causes[c]??c}</small>)}{d.stage==="STABILIZING"&&<small>Encore environ {Math.ceil(d.remaining_seconds??0)} s de stabilité requise</small>}</article>)}</div>
  </section>
  {!!p.exit_summary?.total&&<details className="portfolio-exits"><summary>Pourquoi les positions se ferment-elles ? · durée médiane {elapsed(p.exit_summary.median_seconds??0)}</summary><p>Sur {p.exit_summary.total} clôtures du portefeuille, toutes périodes confondues. Les causes détaillées du garde sont enregistrées à partir de cette mise à jour.</p><ul>{Object.entries(p.exit_summary.reasons).map(([r,n])=><li key={r}>{exits[r]??r} : {n} clôtures</li>)}</ul></details>}
  <p className="panel-note">{p.pair_status}</p>
  {p.allocation_feedback?.enabled&&<section aria-label="Amélioration du capital"><h4>La boucle améliore-t-elle le capital ?</h4>
   <p>Mesurer les clôtures nettes → ajuster l’allocation → transmettre le bilan au prochain lot LLM → tester les descendants → mesurer à nouveau.</p>
   {p.comparison&&<><div className="darwin-kpis"><div><small>CAPITAL DEPUIS LE DÉBUT DU COMPARATIF</small><b>{signed(p.comparison.gain_since_start_eur)} €</b><span>Départ commun : {fmt(p.comparison.start_equity_eur)} €</span></div><div><small>ÉCART AU TÉMOIN À ALLOCATION FIXE</small><b>{signed(p.comparison.delta_vs_fixed_eur)} €</b><span>Témoin virtuel : {fmt(p.comparison.fixed_equity_eur)} €</span></div></div><p>{p.comparison.status==="COLLECTING"?"Collecte en cours : au moins 30 minutes et 10 clôtures par portefeuille avant un bilan descriptif.":p.comparison.status==="CAPITAL_GAIN"?"Capital en hausse sur cette fenêtre et au-dessus du témoin. Ce constat ne prédit pas la suite.":p.comparison.status==="LOWER_LOSS"?"Meilleur résultat que le témoin, mais pas de gain absolu démontré sur cette fenêtre.":"Pas d’amélioration mesurée face au témoin sur cette fenêtre."}</p><p className="panel-note">Comparaison future de l’allocation uniquement : mêmes génomes évolutifs, données et modèle de coûts. Réduire les pertes n’est pas gagner de l’argent ; ce n’est pas une preuve statistique.</p></>}
   <details><summary>Décisions d’allocation automatiques · {p.allocation_feedback.decisions.length} événements récents</summary><p>Budget directionnel : 50 % en exploration ; 25 % après au moins cinq clôtures avec résultat cumulé négatif ; jusqu’à 100 % après vingt clôtures sur trente minutes avec résultat positif sous frais majorés. Les familles réduites continuent à petite taille pour collecter des preuves futures.</p><ul>{[...p.allocation_feedback.decisions].reverse().slice(0,12).map((d,i)=><li key={i}>{new Date(d.ts*1000).toLocaleString()} · {d.group} · budget {d.scale*100} % · {signed(d.net_eur)} € nets sur {d.trades} clôtures.</li>)}</ul></details>
  </section>}

  <details><summary>Comprendre le capital, les frais et les couvertures</summary><p>Le spot est payé comptant ; les perps réservent une marge à 3×. La somme brute des jambes est plafonnée à trois fois la valeur du portefeuille à l’entrée. Un dépassement par mouvement de marché déclenche une tentative de réduction sur carnet frais. Les stratégies sur un même perp sont des allocations virtuelles ; leur exposition exchange serait nette, sans mode hedge par stratégie.</p><p>Au plus 18 allocations directionnelles (100 € chacune au départ) et une paire couverte (250 € par jambe au départ). Les entrées peuvent attendre ; aucune performance positive n’est garantie. Frais taker modélisés : 4,5 bp par fill perp, 7 bp spot, sans réduction de compte. Les deux carnets doivent permettre la quantité entière ; la paire est atomique dans le paper uniquement. Risque de jambe, latence, liquidation et impact réel ne sont pas reproduits.</p><p>Change BCE figé à l’initialisation : {p.fx?`1 EUR = ${p.fx.usd_per_eur} USD (${p.fx.date})`:"en attente"}. USDC/USD supposés à parité ; ce suivi n’est pas un relevé de wallet. Funding proratisé à partir du taux horaire observé, pas un règlement exact de l’exchange. Temps non couvert par ce modèle : {fmt(p.funding_unobserved_seconds,0)} secondes-position.</p><p>La paire spot long / perp short neutralise la quantité de HYPE, pas le risque de basis ni tous les autres risques. Gamma : {p.gamma_status}.</p></details>
  <details><summary>Journal du portefeuille · {p.closed_count} clôtures</summary><div className="darwin-table-wrap"><table className="darwin-table"><thead><tr><th>Clôture</th><th>Stratégie</th><th>Durée</th><th>Net €</th><th>Frais €</th><th>Motif</th></tr></thead><tbody>{[...p.closed].reverse().map(x=><tr key={x.id}><td>{new Date(x.closed_at*1000).toLocaleString()}</td><td><StrategyName id={x.strategy_id}/></td><td>{x.opened_at==null?"—":elapsed(x.closed_at-x.opened_at)}</td><td>{signed(x.net_eur)}</td><td>{fmt(x.fees_eur)}</td><td>{exits[x.reason]??x.reason}{x.exit_context?.causes?.map(c=><small key={c}>{causes[c]??c}</small>)}</td></tr>)}</tbody></table></div></details>
 </section>;
}
