import React, {useEffect, useState} from 'react';
import {API} from './api';
import {Help} from './help';

type Run = {id:string; ts:number; status:string; remote_status?:string; positions_flat?:boolean; open_orders?:number; steps:string[]};
type Preflight = {ready:boolean;account:string;agent_address:string|null;observed_at:number;checks:Record<string,boolean>;plan:{size:number;limit_price:number;notional_usd:number};costs:{maker_bps:number|null;taker_bps:number|null;funding_hourly_bps:number;estimated_maker_usd:number|null};exposure:{projected_usd:number|null;cap_usd:number};account_value_usd:number;book_age_seconds:number};
const labels:Record<string,string>={testnet_network:'Configuration sur testnet',validation_enabled:'Validation testnet autorisée localement',sdk_installed:'SDK officiel installé',account_configured:'Adresse du compte configurée',dedicated_api_wallet:'Clé d’une API wallet dédiée',api_wallet_approved:'API wallet approuvée et non expirée',funded_test_account:'Solde de test suffisant',fresh_book:'Carnet récent et cohérent',fees_available:'Frais du compte disponibles',finite_funding:'Funding disponible',exposure_cap:'Exposition cumulée sous le plafond',minimum_order:'Taille et minimum de l’ordre valides',clean_test_account:'Compte de test sans position ni ordre',previous_run_resolved:'Aucun essai précédent à rapprocher'};
const status:Record<string,string>={PASSED:'Ordre et annulation vérifiés',FAILED:'Essai rejeté',BLOCKED:'Bloqué avant envoi',RUNNING:'Validation en cours',RECONCILIATION_REQUIRED:'Rapprochement nécessaire'};
const n=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('fr-FR',{maximumFractionDigits:5});

export function TestnetValidation(){
 const [coin,setCoin]=useState('BTC'),[amount,setAmount]=useState(12),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [preflight,setPreflight]=useState<Preflight|null>(null),[runs,setRuns]=useState<Run[]>([]),[ack,setAck]=useState(false);
 async function call(path:string,body?:unknown){const r=await fetch(`${API}/api/hyperliquid/validation${path}`,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).detail??'Testnet indisponible');return r.json();}
 async function history(){const data=await call('/history');setRuns(data.runs);}
 useEffect(()=>{void history().catch(()=>setError('Historique indisponible.'));},[]);
 async function action(kind:'preflight'|'run'|'reconcile',id?:string){setBusy(true);setError('');try{const data=await call(kind==='reconcile'?`/${id}/reconcile`:`/${kind}`,kind==='reconcile'?{}:{coin,notional_usd:amount,...(kind==='run'?{acknowledgement:'TESTNET_ORDER_AND_CANCEL'}:{})});if(kind==='preflight')setPreflight(data);else{setAck(false);setPreflight(data.preflight??null);await history();}}catch(e){setError(e instanceof Error?e.message:'Échec de validation');await history().catch(()=>{});}finally{setBusy(false);}}
 return <section className="testnet-validation" aria-label="Préparation et validation testnet">
  <header><span className="factory-eyebrow">EXÉCUTION · ÉTAPE TESTNET</span><h3>Préparer, vérifier, puis tester</h3><p>Un parcours indépendant du paper trading. Le réseau de ce panneau est toujours le testnet ; le sélecteur du compte ci-dessus ne le modifie pas.</p></header>
  <div className="wallet-steps"><span><b>1 · API wallet</b>À approuver sur Hyperliquid testnet</span><span><b>2 · Contrôles</b>Compte, frais, funding, exposition</span><span><b>3 · Ordre puis annulation</b>Essai manuel et résultat conservé</span></div>
  <details><summary>Configurer le compte de test et la clé locale</summary><ol><li>Ouvre le testnet officiel, connecte ton wallet et approvisionne le compte en fonds de test selon les conditions du faucet.</li><li>Dans la page API officielle, crée et approuve une API wallet dédiée au testnet. Cette approbation reste une action dans ton wallet.</li><li>Dans le fichier .env local : renseigne HYPERLIQUID_ACCOUNT_ADDRESS (compte principal), HYPERLIQUID_API_PRIVATE_KEY (clé de l’API wallet), HYPERLIQUID_NETWORK=testnet et HYPERLIQUID_TESTNET_VALIDATION=true. Garde HYPERLIQUID_ENABLED=false. Redémarre Darwin après modification.</li><li>Utilise un compte de test sans position ni ordre pour que le rapprochement soit vérifiable.</li></ol><p>Aucune clé ne doit être collée dans cette page, les agents ou la conversation.</p></details>
  <p><a href="https://app.hyperliquid-testnet.xyz" target="_blank" rel="noreferrer">Ouvrir le testnet ↗</a> · <a href="https://app.hyperliquid-testnet.xyz/API" target="_blank" rel="noreferrer">Approuver une API wallet testnet ↗</a></p>
  <div className="wallet-steps"><label>Marché<select disabled={busy} value={coin} onChange={e=>{setCoin(e.target.value);setPreflight(null);setAck(false);}}>{['BTC','ETH','SOL'].map(c=><option key={c}>{c}</option>)}</select></label><label>Nominal de test · USD<input type="number" min={11} max={100} disabled={busy} value={amount} onChange={e=>{setAmount(Number(e.target.value));setPreflight(null);setAck(false);}}/></label></div>
  <button disabled={busy||!Number.isFinite(amount)||amount<11||amount>100} onClick={()=>void action('preflight')}>{busy?'Vérification…':'Vérifier la préparation · sans ordre'}</button>
  {error&&<p role="alert">{error}</p>}
  {preflight&&<><h4>{preflight.ready?'Prêt pour un essai testnet':'Préparation incomplète'}</h4><p>Compte configuré : {preflight.account||'non renseigné'} · API wallet : {preflight.agent_address||'clé absente ou invalide'}</p><ul className="validation-checks">{Object.entries(preflight.checks).map(([key,ok])=><li key={key}><span aria-label={ok?'Validé':'Bloqué'}>{ok?'✓':'○'}</span> {labels[key]??key}</li>)}</ul>
   <div className="wallet-steps"><span><b>Frais maker / taker</b>{n(preflight.costs.maker_bps)} / {n(preflight.costs.taker_bps)} bp</span><span><b>Funding horaire actuel</b>{n(preflight.costs.funding_hourly_bps)} bp<Help label="Funding testnet" text="Taux courant du testnet. Positif : les longs paient les shorts ; négatif : l’inverse. Ce taux évolue et ne prédit pas le coût futur. Il n’est pas injecté dans la comptabilité paper existante."/></span><span><b>Exposition après ordre</b>{n(preflight.exposure.projected_usd)} / {n(preflight.exposure.cap_usd)} USD</span></div>
   <p>Âge du carnet : {n(preflight.book_age_seconds)} s · limite de fraîcheur : 10 s.</p><p>Plan indicatif : achat limite post-only de {n(preflight.plan.size)} {coin} à {n(preflight.plan.limit_price)} USD, nominal {n(preflight.plan.notional_usd)} USD. Les contrôles sont recalculés juste avant l’envoi.</p>
   <p>Le prix est placé sous le meilleur achat, puis l’ordre est annulé. Un mouvement rapide peut néanmoins l’exécuter : le parcours signale alors la position et bloque tout nouvel essai, sans clôture automatique.</p>
   <label><input type="checkbox" disabled={busy||!preflight.ready} checked={ack} onChange={e=>setAck(e.target.checked)}/> J’autorise cet ordre de test et son annulation sur testnet.</label><button disabled={busy||!preflight.ready||!ack} onClick={()=>void action('run')}>Lancer l’essai testnet</button>
  </>}
  <h4>Résultats des essais</h4>{runs.length===0?<p>Aucun ordre de validation envoyé. Les tests logiciels ne valent pas validation de bout en bout sur l’exchange.</p>:runs.map(r=><article key={r.id}><strong>{status[r.status]??r.status}</strong> · {new Date(r.ts*1000).toLocaleString('fr-FR')}<p>État exchange : {r.remote_status??'non confirmé'} · position nulle : {r.positions_flat==null?'inconnue':r.positions_flat?'oui':'non'} · ordres ouverts : {r.open_orders??'inconnu'}</p><details><summary>Journal de cet essai</summary><ul>{r.steps.map((s,i)=><li key={i}>{s}</li>)}</ul></details>{(r.status==='RECONCILIATION_REQUIRED'||r.status==='RUNNING')&&<button disabled={busy} onClick={()=>void action('reconcile',r.id)}>Annuler cet ordre et revérifier</button>}</article>)}
  <p><strong>Passage au réel : désactivé.</strong> Un essai réussi valide l’envoi, l’annulation et le rapprochement de cet ordre testnet. Il ne valide ni la rentabilité, ni toutes les conditions d’exécution réelle. L’activation mainnet reste une étape séparée.</p>
 </section>;
}
